package com.hospital.scheduler.service;

import com.hospital.scheduler.dto.request.AutoScheduleRequestDTO;
import com.hospital.scheduler.dto.response.AlgorithmMetricsDTO;
import com.hospital.scheduler.dto.response.AutoScheduleResponse;
import com.hospital.scheduler.entity.*;
import com.hospital.scheduler.exception.BadRequestException;
import com.hospital.scheduler.exception.ResourceNotFoundException;
import com.hospital.scheduler.repository.*;
import com.hospital.scheduler.util.CompensationDateCalculator;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Transactional
public class AutoSchedulingService {

    private final ScheduleRepository scheduleRepository;
    private final SchedulePeriodRepository periodRepository;
    private final StaffRepository staffRepository;
    private final ShiftRequirementRepository requirementRepository;
    private final CompensationDayRepository compensationDayRepository;
    private final AlgorithmMetricsRepository metricsRepository;
    private final ConflictDetectionService conflictDetectionService;
    private final AuditHistoryService auditHistoryService;
    private final CompensationDateCalculator compensationDateCalculator;

    // Track assignments within current preview/schedule run for conflict detection
    // Key: "staffId_workDate", Value: set of assigned shiftTypeIds
    private Map<String, Set<String>> inMemoryAssignments = new HashMap<>();
    // Track compensation days for current run (shiftDate) for each staff to prevent L02/L03/L04 on those days
    private Set<String> inMemoryCompensationShiftDates = new HashSet<>();
    // Track ALL compensation days (shiftDate) - both from existing DB and current run - to prevent L01 assignment
    private Set<String> allCompensationShiftDates = new HashSet<>();

    public AutoScheduleResponse previewSchedule(AutoScheduleRequestDTO request) {
        inMemoryAssignments = new HashMap<>();
        inMemoryCompensationShiftDates = new HashSet<>();
        allCompensationShiftDates = new HashSet<>();
        return runScheduling(request, false);
    }

    public AutoScheduleResponse autoSchedule(AutoScheduleRequestDTO request) {
        inMemoryAssignments = new HashMap<>();
        inMemoryCompensationShiftDates = new HashSet<>();
        allCompensationShiftDates = new HashSet<>();
        return runScheduling(request, true);
    }

    public AutoScheduleResponse applyPreviewSchedule(com.hospital.scheduler.dto.request.AutoScheduleApplyPreviewRequestDTO request) {
        SchedulePeriod period = periodRepository.findById(request.getPeriodId())
                .orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy kỳ lịch với ID: " + request.getPeriodId()));

        if (period.getStatus() != SchedulePeriod.PeriodStatus.DRAFT) {
            throw new BadRequestException("Chỉ có thể áp dụng bản nháp khi kỳ lịch ở trạng thái DRAFT");
        }

        List<Schedule> savedSchedules = new ArrayList<>();
        long startTime = System.currentTimeMillis();

        for (var item : request.getSchedules()) {
            Staff staff = staffRepository.findById(item.getStaffId())
                    .orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy nhân sự với ID: " + item.getStaffId()));
            ShiftRequirement requirement = requirementRepository.findByPeriodId(period.getId()).stream()
                    .filter(req -> req.getWorkDate().toString().equals(item.getWorkDate()))
                    .filter(req -> req.getShiftType().getId().equals(item.getShiftTypeId()))
                    .findFirst()
                    .orElse(null);
            ShiftType shiftType = requirement != null ? requirement.getShiftType() : null;
            if (shiftType == null) {
                throw new BadRequestException("Không tìm thấy ca trực phù hợp cho ngày " + item.getWorkDate());
            }

            Schedule schedule = Schedule.builder()
                    .period(period)
                    .staff(staff)
                    .shiftType(shiftType)
                    .workDate(LocalDate.parse(item.getWorkDate()))
                    .requirement(requirement)
                    .hasConflict(false)
                    .build();

            // Skip compensation day and shift-type conflict checks because schedules were already generated by
          // the auto-scheduling algorithm which already tracked in-memory conflicts.
            // Only check leave requests since those can change between preview and apply.
            conflictDetectionService.validateAndThrow(staff.getId(), LocalDate.parse(item.getWorkDate()), shiftType.getId(), null, null);

            Schedule saved = scheduleRepository.save(schedule);
            if (ConflictDetectionService.SHIFT_TYPE_L01.equals(shiftType.getId())) {
                createCompensationDayForAuto(saved);
            }
            auditHistoryService.logAction("schedule", saved.getId(), AuditHistory.ActionType.INSERT, null, saved, null);
            savedSchedules.add(saved);
        }

        List<AutoScheduleResponse.ScheduleSummary> summaries = savedSchedules.stream()
                .map(s -> AutoScheduleResponse.ScheduleSummary.builder()
                        .scheduleId(s.getId())
                        .staffId(s.getStaff().getId())
                        .staffName(s.getStaff().getFullName())
                        .workDate(s.getWorkDate().toString())
                        .shiftTypeId(s.getShiftType().getId())
                        .shiftTypeName(s.getShiftType().getName())
                        .build())
                .toList();

        int totalRequired = request.getSchedules().size();
        BigDecimal coverageRate = totalRequired > 0
                ? BigDecimal.valueOf((double) savedSchedules.size() / totalRequired * 100)
                : BigDecimal.ZERO;
        BigDecimal balanceScore = calculateBalanceScore(savedSchedules, (int) savedSchedules.stream()
                .map(s -> s.getStaff().getId())
                .distinct()
                .count());

        long executionTime = System.currentTimeMillis() - startTime;

        return AutoScheduleResponse.builder()
                .success(true)
                .message("Đã áp dụng bản nháp đã chỉnh sửa")
                .periodId(period.getId())
                .algorithmType(request.getAlgorithmType())
                .executionTimeMs((int) executionTime)
                .coverageRate(coverageRate.setScale(2, RoundingMode.HALF_UP))
                .balanceScore(balanceScore.setScale(2, RoundingMode.HALF_UP))
                .conflictCount(0)
                .totalSchedulesCreated(savedSchedules.size())
                .schedules(summaries)
                .executedAt(LocalDateTime.now())
                .build();
    }

    private AutoScheduleResponse runScheduling(AutoScheduleRequestDTO request, boolean save) {
        long startTime = System.currentTimeMillis();

        SchedulePeriod period = periodRepository.findById(request.getPeriodId())
                .orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy kỳ lịch với ID: " + request.getPeriodId()));

        if (period.getStatus() != SchedulePeriod.PeriodStatus.DRAFT) {
            throw new BadRequestException("Chỉ có thể xếp lịch tự động khi kỳ lịch ở trạng thái DRAFT");
        }

        List<Staff> activeStaff = staffRepository.findByIsActiveTrue();
        if (request.getExcludedStaffIds() != null && !request.getExcludedStaffIds().isEmpty()) {
            Set<Integer> excluded = new HashSet<>(request.getExcludedStaffIds());
            activeStaff = activeStaff.stream()
                    .filter(s -> !excluded.contains(s.getId()))
                    .collect(Collectors.toList());
        }
        List<ShiftRequirement> requirements = new ArrayList<>(requirementRepository.findByPeriodId(period.getId()));

        // Pre-load all existing compensation days (from published periods) so greedy doesn't assign L01 on a day
        // that is a compensation day for any staff member (from their L01 in a previous period)
        List<CompensationDay> existingCompDays = compensationDayRepository.findAll();
        for (CompensationDay cd : existingCompDays) {
            allCompensationShiftDates.add(cd.getStaff().getId() + "_" + cd.getCompensationDate().toString());
        }

        // P2-8: Enforce L01→L02→L03→L04 processing order per spec
        // L01 must be assigned first to reserve compensation days and avoid L01↔L02 conflicts
        requirements.sort(Comparator.comparingInt((ShiftRequirement r) -> {
            String id = r.getShiftType().getId();
            if (ConflictDetectionService.SHIFT_TYPE_L01.equals(id)) return 0;
            if (ConflictDetectionService.SHIFT_TYPE_L02.equals(id)) return 1;
            if (ConflictDetectionService.SHIFT_TYPE_L03.equals(id)) return 2;
            if (ConflictDetectionService.SHIFT_TYPE_L04.equals(id)) return 3;
            return 4;
        }));

        if (activeStaff.isEmpty()) {
            throw new BadRequestException("Không có nhân sự nào đang hoạt động");
        }

        String algorithmType = request.getAlgorithmType() != null ? request.getAlgorithmType().toUpperCase() : "GREEDY";

        List<Schedule> createdSchedules;
        if ("ROUND_ROBIN".equals(algorithmType)) {
            createdSchedules = runRoundRobin(period, requirements, activeStaff, save,
                    request.getExcludedStaffIds() != null ? new HashSet<>(request.getExcludedStaffIds()) : null);
        } else if ("BACKTRACKING".equals(algorithmType)) {
            createdSchedules = runBacktracking(period, requirements, activeStaff, save,
                    request.getMaxIterations() != null ? request.getMaxIterations() : 1000,
                    request.getExcludedStaffIds() != null ? new HashSet<>(request.getExcludedStaffIds()) : null);
        } else {
            createdSchedules = runGreedy(period, requirements, activeStaff, save,
                    request.getExcludedStaffIds() != null ? new HashSet<>(request.getExcludedStaffIds()) : null);
        }
        List<String> warnings = buildWarnings(requirements, createdSchedules);

        long executionTime = System.currentTimeMillis() - startTime;
        int totalRequired = requirements.size();
        BigDecimal coverageRate = totalRequired > 0
                ? BigDecimal.valueOf((double) createdSchedules.size() / totalRequired * 100)
                : BigDecimal.ZERO;
        int distinctStaffAssigned = (int) createdSchedules.stream().map(s -> s.getStaff().getId()).distinct().count();
        int staffCount = distinctStaffAssigned > 0 ? distinctStaffAssigned : 1;
        BigDecimal balanceScore = calculateBalanceScore(createdSchedules, staffCount);

        if (save) {
            saveMetrics(period, algorithmType, (int) executionTime, coverageRate, balanceScore, warnings.size());
        }

        List<AutoScheduleResponse.ScheduleSummary> scheduleSummaries = createdSchedules.stream()
                .map(s -> AutoScheduleResponse.ScheduleSummary.builder()
                        .scheduleId(s.getId())
                        .staffId(s.getStaff().getId())
                        .staffName(s.getStaff().getFullName())
                        .workDate(s.getWorkDate().toString())
                        .shiftTypeId(s.getShiftType().getId())
                        .shiftTypeName(s.getShiftType().getName())
                        .build())
                .collect(Collectors.toList());

        String actionType = save ? "Xếp lịch tự động thành công" : "Xem trước lịch";

        return AutoScheduleResponse.builder()
                .success(true)
                .message(warnings.isEmpty() ? actionType : actionType + " với " + warnings.size() + " cảnh báo")
                .periodId(period.getId())
                .algorithmType(algorithmType)
                .executionTimeMs((int) executionTime)
                .coverageRate(coverageRate.setScale(2, RoundingMode.HALF_UP))
                .balanceScore(balanceScore.setScale(2, RoundingMode.HALF_UP))
                .conflictCount(warnings.size())
                .totalSchedulesCreated(createdSchedules.size())
                .schedules(scheduleSummaries)
                .executedAt(LocalDateTime.now())
                .build();
    }

    // ==================== GREEDY ALGORITHM ====================
    private List<Schedule> runGreedy(SchedulePeriod period, List<ShiftRequirement> requirements,
                                     List<Staff> activeStaff, boolean save,
                                     Set<Integer> excludedStaffIds) {
        List<Schedule> createdSchedules = new ArrayList<>();
        Map<LocalDate, List<ShiftRequirement>> requirementsByDate = groupRequirementsByDate(requirements);

        LocalDate currentDate = period.getStartDate();
        while (!currentDate.isAfter(period.getEndDate())) {
            List<ShiftRequirement> todayReqs = sortRequirementsByPriority(
                    requirementsByDate.getOrDefault(currentDate, Collections.emptyList()));

            Set<Integer> assignedStaffIds = new HashSet<>();
            for (ShiftRequirement req : todayReqs) {
                final LocalDate workDate = currentDate;
                List<Staff> eligibleStaff = filterAndSortEligibleStaff(activeStaff, req, excludedStaffIds, !save,
                        Comparator.comparingLong(s -> scheduleRepository.countByStaffIdAndPeriodId(s.getId(), period.getId())));

                int toAssign = Math.min(req.getRequiredStaffCount(), eligibleStaff.size());
                for (int i = 0; i < toAssign; i++) {
                    Staff staff = eligibleStaff.get(i);
                    Schedule saved = buildAndSaveSchedule(period, staff, req, workDate, save, createdSchedules);
                    trackAssignment(staff, workDate, req.getShiftType().getId());
                    assignedStaffIds.add(staff.getId());
                    if (save && ConflictDetectionService.SHIFT_TYPE_L01.equals(req.getShiftType().getId())) {
                        createCompensationDayForAuto(saved);
                    }
                }
            }
            currentDate = currentDate.plusDays(1);
        }
        return createdSchedules;
    }

    // ==================== ROUND ROBIN ALGORITHM ====================
    private List<Schedule> runRoundRobin(SchedulePeriod period, List<ShiftRequirement> requirements,
                                          List<Staff> activeStaff, boolean save,
                                          Set<Integer> excludedStaffIds) {
        List<Schedule> createdSchedules = new ArrayList<>();
        Map<Integer, Integer> staffRotationIndex = new HashMap<>();
        for (Staff staff : activeStaff) {
            staffRotationIndex.put(staff.getId(), 0);
        }

        Map<LocalDate, List<ShiftRequirement>> requirementsByDate = groupRequirementsByDate(requirements);

        LocalDate currentDate = period.getStartDate();
        while (!currentDate.isAfter(period.getEndDate())) {
            List<ShiftRequirement> todayReqs = sortRequirementsByPriority(
                    requirementsByDate.getOrDefault(currentDate, Collections.emptyList()));

            Set<Integer> assignedStaffIds = new HashSet<>();
            for (ShiftRequirement req : todayReqs) {
                final LocalDate workDate = currentDate;
                List<Staff> eligibleStaff = filterAndSortEligibleStaff(activeStaff, req, excludedStaffIds, !save,
                        Comparator.comparingInt(s -> staffRotationIndex.getOrDefault(s.getId(), 0)));

                int toAssign = Math.min(req.getRequiredStaffCount(), eligibleStaff.size());
                for (int i = 0; i < toAssign; i++) {
                    Staff staff = eligibleStaff.get(i);
                    Schedule saved = buildAndSaveSchedule(period, staff, req, workDate, save, createdSchedules);
                    trackAssignment(staff, workDate, req.getShiftType().getId());
                    assignedStaffIds.add(staff.getId());
                    staffRotationIndex.merge(staff.getId(), 1, Integer::sum);
                    if (save && ConflictDetectionService.SHIFT_TYPE_L01.equals(req.getShiftType().getId())) {
                        createCompensationDayForAuto(saved);
                    }
                }
            }
            currentDate = currentDate.plusDays(1);
        }
        return createdSchedules;
    }

    // ==================== BACKTRACKING ALGORITHM ====================
    private List<Schedule> runBacktracking(SchedulePeriod period, List<ShiftRequirement> requirements,
                                            List<Staff> activeStaff, boolean save, int maxIterations,
                                            Set<Integer> excludedStaffIds) {
        List<Schedule> bestSolution = new ArrayList<>();
        List<Schedule> currentSolution = new ArrayList<>();
        // Track in-memory assignments for backtracking: staffId_workDate -> set of shiftTypeIds
        List<Map<String, Set<String>>> assignmentHistory = new ArrayList<>();
        assignmentHistory.add(new HashMap<>());

        List<ShiftRequirement> sortedRequirements = requirements.stream()
                .sorted(Comparator.comparingInt((ShiftRequirement r) -> {
                    String id = r.getShiftType().getId();
                    if (ConflictDetectionService.SHIFT_TYPE_L01.equals(id)) return 0;
                    if (ConflictDetectionService.SHIFT_TYPE_L02.equals(id)) return 1;
                    if (ConflictDetectionService.SHIFT_TYPE_L03.equals(id)) return 2;
                    if (ConflictDetectionService.SHIFT_TYPE_L04.equals(id)) return 3;
                    return 4;
                })
                        .thenComparing((ShiftRequirement r) -> r.getSpecialty() != null ? 0 : 1)
                        .thenComparing(r -> r.getRequiredStaffCount())
                        .reversed())
                .collect(Collectors.toList());

        backtrack(period, sortedRequirements, activeStaff, 0, currentSolution, bestSolution,
                  new HashMap<>(), assignmentHistory, maxIterations, excludedStaffIds, save);

        if (save) {
            for (Schedule schedule : bestSolution) {
                Schedule saved = scheduleRepository.save(schedule);
                schedule.setId(saved.getId());
                if (ConflictDetectionService.SHIFT_TYPE_L01.equals(schedule.getShiftType().getId())) {
                    createCompensationDayForAuto(saved);
                }
                auditHistoryService.logAction("schedule", saved.getId(), AuditHistory.ActionType.INSERT, null, saved, null);
            }
        } else {
            for (Schedule schedule : bestSolution) {
                schedule.setId(null);
            }
        }

        return save ? bestSolution : bestSolution;
    }

    private void backtrack(SchedulePeriod period, List<ShiftRequirement> requirements,
                           List<Staff> activeStaff, int index,
                           List<Schedule> currentSolution, List<Schedule> bestSolution,
                           Map<Integer, Integer> staffWorkload,
                           List<Map<String, Set<String>>> assignmentHistory, int maxIterations,
                           Set<Integer> excludedStaffIds, boolean save) {

        if (maxIterations <= 0) return;

        if (currentSolution.size() > bestSolution.size()) {
            bestSolution.clear();
            bestSolution.addAll(currentSolution);
        }

        if (index >= requirements.size()) return;

        ShiftRequirement req = requirements.get(index);
        LocalDate workDate = req.getWorkDate();

        List<Staff> candidates = conflictDetectionService.findReplacements(
                period.getId(), workDate, req.getShiftType().getId(), null,
                req.getRequiredStaffCount(), excludedStaffIds, !save);

        candidates = filterBySpecialty(candidates, req.getSpecialty() != null ? req.getSpecialty().getId() : null);

        candidates.sort(Comparator.comparingInt(s -> staffWorkload.getOrDefault(s.getId(), 0)));

        int staffToAssign = Math.min(req.getRequiredStaffCount(), candidates.size());

        for (int i = 0; i < staffToAssign; i++) {
            Staff staff = candidates.get(i);

            Map<String, Set<String>> currentAssignments = assignmentHistory.get(assignmentHistory.size() - 1);

            if (hasInMemoryConflictForBacktrack(staff.getId(), workDate, req.getShiftType().getId(), currentAssignments)) {
                continue;
            }

            Schedule schedule = buildScheduleForBacktrack(period, staff, req.getShiftType(), workDate, req);
            if (schedule == null) continue;

            currentSolution.add(schedule);
            staffWorkload.merge(staff.getId(), 1, Integer::sum);

            Map<String, Set<String>> newAssignments = new HashMap<>(currentAssignments);
            String key = staff.getId() + "_" + workDate;
            newAssignments.computeIfAbsent(key, k -> new HashSet<>()).add(req.getShiftType().getId());
            assignmentHistory.add(newAssignments);

            backtrack(period, requirements, activeStaff, index + 1,
                    currentSolution, bestSolution, staffWorkload, assignmentHistory,
                    maxIterations - 1, excludedStaffIds, save);

            assignmentHistory.remove(assignmentHistory.size() - 1);
            staffWorkload.merge(staff.getId(), -1, (oldVal, ignore) -> oldVal <= 0 ? 0 : oldVal);
            currentSolution.remove(currentSolution.size() - 1);
        }
    }

    private boolean hasInMemoryConflictForBacktrack(Integer staffId, LocalDate workDate, String shiftTypeId,
                                                    Map<String, Set<String>> assignments) {
        String key = staffId + "_" + workDate;
        Set<String> existingShifts = assignments.get(key);
        if (existingShifts == null) return false;

        for (String existingId : existingShifts) {
            if (ConflictDetectionService.SHIFT_TYPE_L01.equals(shiftTypeId)) {
                if (ConflictDetectionService.SHIFT_TYPE_L02.equals(existingId) || ConflictDetectionService.SHIFT_TYPE_L03.equals(existingId) || ConflictDetectionService.SHIFT_TYPE_L04.equals(existingId)) {
                    return true;
                }
            }
            if (ConflictDetectionService.SHIFT_TYPE_L02.equals(shiftTypeId)) {
                if (ConflictDetectionService.SHIFT_TYPE_L01.equals(existingId)) return true;
            }
            if (ConflictDetectionService.SHIFT_TYPE_L03.equals(shiftTypeId) || ConflictDetectionService.SHIFT_TYPE_L04.equals(shiftTypeId)) {
                if ((ConflictDetectionService.SHIFT_TYPE_L03.equals(existingId) && ConflictDetectionService.SHIFT_TYPE_L04.equals(shiftTypeId)) ||
                    (ConflictDetectionService.SHIFT_TYPE_L04.equals(existingId) && ConflictDetectionService.SHIFT_TYPE_L03.equals(shiftTypeId))) {
                    return true;
                }
                if (ConflictDetectionService.SHIFT_TYPE_L01.equals(existingId)) return true;
            }
        }
        return false;
    }

    private Schedule buildScheduleForBacktrack(SchedulePeriod period, Staff staff, ShiftType shiftType,
                                               LocalDate workDate, ShiftRequirement requirement) {
        return Schedule.builder()
                .period(period)
                .staff(staff)
                .shiftType(shiftType)
                .workDate(workDate)
                .requirement(requirement)
                .hasConflict(false)
                .build();
    }

    // ==================== M07-F06: Báo cáo ngày chưa phân công ====================
    public Map<String, Object> getUnassignedDaysReport(Integer periodId) {
        SchedulePeriod period = periodRepository.findById(periodId)
                .orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy kỳ lịch với ID: " + periodId));

        List<ShiftRequirement> requirements = requirementRepository.findByPeriodId(periodId);
        List<Schedule> schedules = scheduleRepository.findByPeriodId(periodId);

        Map<String, List<ShiftRequirement>> requirementsByDateAndShift = new LinkedHashMap<>();
        for (ShiftRequirement req : requirements) {
            String key = req.getWorkDate() + "_" + req.getShiftType().getId();
            requirementsByDateAndShift.computeIfAbsent(key, k -> new ArrayList<>()).add(req);
        }

        Map<String, List<Schedule>> schedulesByDateAndShift = new LinkedHashMap<>();
        for (Schedule s : schedules) {
            String key = s.getWorkDate() + "_" + s.getShiftType().getId();
            schedulesByDateAndShift.computeIfAbsent(key, k -> new ArrayList<>()).add(s);
        }

        List<Map<String, Object>> unassignedDays = new ArrayList<>();

        for (Map.Entry<String, List<ShiftRequirement>> entry : requirementsByDateAndShift.entrySet()) {
            String key = entry.getKey();
            List<ShiftRequirement> reqs = entry.getValue();
            List<Schedule> assigned = schedulesByDateAndShift.getOrDefault(key, Collections.emptyList());

            for (ShiftRequirement req : reqs) {
                int required = req.getRequiredStaffCount();
                int assignedCount = (int) assigned.stream()
                        .filter(s -> s.getShiftType().getId().equals(req.getShiftType().getId()))
                        .count();

                if (assignedCount < required) {
                    Map<String, Object> dayInfo = new LinkedHashMap<>();
                    dayInfo.put("workDate", req.getWorkDate());
                    dayInfo.put("dayOfWeek", getDayOfWeekVietnamese(req.getWorkDate().getDayOfWeek().getValue()));
                    dayInfo.put("shiftTypeId", req.getShiftType().getId());
                    dayInfo.put("shiftTypeName", req.getShiftType().getName());
                    dayInfo.put("specialty", req.getSpecialty() != null ? req.getSpecialty().getName() : null);
                    dayInfo.put("requiredStaffCount", required);
                    dayInfo.put("assignedStaffCount", assignedCount);
                    dayInfo.put("missingCount", required - assignedCount);
                    unassignedDays.add(dayInfo);
                }
            }
        }

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("periodId", periodId);
        result.put("periodName", period.getPeriodName());
        result.put("startDate", period.getStartDate());
        result.put("endDate", period.getEndDate());
        result.put("totalUnassignedDays", unassignedDays.size());
        result.put("unassignedDays", unassignedDays);

        return result;
    }

    // ==================== M07-F08: Đề xuất người thay thế ====================
    public Map<String, Object> suggestReplacements(Integer scheduleId) {
        Schedule original = scheduleRepository.findById(scheduleId)
                .orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy lịch với ID: " + scheduleId));

        List<Staff> allStaff = staffRepository.findByIsActiveTrue();

        List<Map<String, Object>> suggestions = new ArrayList<>();

        for (Staff candidate : allStaff) {
            if (candidate.getId().equals(original.getStaff().getId())) continue;

            if (original.getStaff().getSpecialty() != null) {
                if (candidate.getSpecialty() == null ||
                        !candidate.getSpecialty().getId().equals(original.getStaff().getSpecialty().getId())) {
                    continue;
                }
            }

            List<String> conflicts = conflictDetectionService.detectAllConflicts(
                    candidate.getId(), original.getWorkDate(), original.getShiftType().getId(), scheduleId);

            if (conflicts.isEmpty()) {
                long currentWorkload = scheduleRepository.countByStaffIdAndPeriodId(
                        candidate.getId(), original.getPeriod().getId());

                Map<String, Object> suggestion = new LinkedHashMap<>();
                suggestion.put("staffId", candidate.getId());
                suggestion.put("staffName", candidate.getFullName());
                suggestion.put("specialty", candidate.getSpecialty() != null ? candidate.getSpecialty().getName() : null);
                suggestion.put("currentWorkload", currentWorkload);
                suggestion.put("conflicts", conflicts);
                suggestion.put("isAvailable", true);
                suggestions.add(suggestion);
            } else {
                Map<String, Object> suggestion = new LinkedHashMap<>();
                suggestion.put("staffId", candidate.getId());
                suggestion.put("staffName", candidate.getFullName());
                suggestion.put("specialty", candidate.getSpecialty() != null ? candidate.getSpecialty().getName() : null);
                suggestion.put("currentWorkload", scheduleRepository.countByStaffIdAndPeriodId(
                        candidate.getId(), original.getPeriod().getId()));
                suggestion.put("conflicts", conflicts);
                suggestion.put("isAvailable", false);
                suggestions.add(suggestion);
            }
        }

        suggestions.sort(Comparator.comparing(m -> !(Boolean) m.get("isAvailable")));

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("originalScheduleId", scheduleId);
        result.put("originalStaffId", original.getStaff().getId());
        result.put("originalStaffName", original.getStaff().getFullName());
        result.put("workDate", original.getWorkDate());
        result.put("shiftTypeId", original.getShiftType().getId());
        result.put("shiftTypeName", original.getShiftType().getName());
        result.put("totalCandidates", suggestions.size());
        result.put("availableCount", (int) suggestions.stream().filter(m -> (Boolean) m.get("isAvailable")).count());
        result.put("suggestions", suggestions);

        return result;
    }

    // ==================== M07-F09: Data biểu đồ cân bằng tải ====================
    public Map<String, Object> getWorkloadChartData(Integer periodId) {
        SchedulePeriod period = periodRepository.findById(periodId)
                .orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy kỳ lịch với ID: " + periodId));

        List<Staff> activeStaff = staffRepository.findByIsActiveTrue();
        List<Schedule> schedules = scheduleRepository.findByPeriodId(periodId);

        List<Map<String, Object>> staffWorkloadData = new ArrayList<>();

        for (Staff staff : activeStaff) {
            List<Schedule> staffSchedules = schedules.stream()
                    .filter(s -> s.getStaff().getId().equals(staff.getId()))
                    .collect(Collectors.toList());

            long L01Count = staffSchedules.stream().filter(s -> ConflictDetectionService.SHIFT_TYPE_L01.equals(s.getShiftType().getId())).count();
            long L02Count = staffSchedules.stream().filter(s -> ConflictDetectionService.SHIFT_TYPE_L02.equals(s.getShiftType().getId())).count();
            long L03Count = staffSchedules.stream().filter(s -> ConflictDetectionService.SHIFT_TYPE_L03.equals(s.getShiftType().getId())).count();
            long L04Count = staffSchedules.stream().filter(s -> ConflictDetectionService.SHIFT_TYPE_L04.equals(s.getShiftType().getId())).count();

            Map<String, Object> data = new LinkedHashMap<>();
            data.put("staffId", staff.getId());
            data.put("staffName", staff.getFullName());
            data.put("specialty", staff.getSpecialty() != null ? staff.getSpecialty().getName() : null);
            data.put("totalShifts", staffSchedules.size());
            data.put(ConflictDetectionService.SHIFT_TYPE_L01, L01Count);
            data.put(ConflictDetectionService.SHIFT_TYPE_L02, L02Count);
            data.put(ConflictDetectionService.SHIFT_TYPE_L03, L03Count);
            data.put(ConflictDetectionService.SHIFT_TYPE_L04, L04Count);
            data.put("workloadPercentage", schedules.isEmpty() ? 0.0 :
                    Math.round((double) staffSchedules.size() / schedules.size() * 10000.0) / 100.0);

            staffWorkloadData.add(data);
        }

        staffWorkloadData.sort((a, b) -> {
            int t1 = ((Number) a.get("totalShifts")).intValue();
            int t2 = ((Number) b.get("totalShifts")).intValue();
            return Integer.compare(t2, t1);
        });

        double avgWorkload = schedules.isEmpty() ? 0.0 :
                Math.round((double) schedules.size() / activeStaff.size() * 100.0) / 100.0;

        long minWorkload = staffWorkloadData.stream()
                .mapToLong(m -> ((Number) m.get("totalShifts")).longValue())
                .min().orElse(0);
        long maxWorkload = staffWorkloadData.stream()
                .mapToLong(m -> ((Number) m.get("totalShifts")).longValue())
                .max().orElse(0);

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("periodId", periodId);
        result.put("periodName", period.getPeriodName());
        result.put("startDate", period.getStartDate());
        result.put("endDate", period.getEndDate());
        result.put("totalSchedules", schedules.size());
        result.put("totalStaff", activeStaff.size());
        result.put("averageWorkload", avgWorkload);
        result.put("minWorkload", minWorkload);
        result.put("maxWorkload", maxWorkload);
        result.put("staffWorkloadData", staffWorkloadData);

        return result;
    }

    // ==================== HELPER METHODS ====================
    private List<String> buildWarnings(List<ShiftRequirement> requirements, List<Schedule> schedules) {
        List<String> warnings = new ArrayList<>();

        Map<String, Long> assignedCount = schedules.stream()
                .collect(Collectors.groupingBy(
                        s -> s.getWorkDate() + "_" + s.getShiftType().getId(),
                        Collectors.counting()));

        for (ShiftRequirement req : requirements) {
            String key = req.getWorkDate() + "_" + req.getShiftType().getId();
            long assigned = assignedCount.getOrDefault(key, 0L);
            if (assigned < req.getRequiredStaffCount()) {
                warnings.add(String.format("Ngày %s (%s), ca %s: thiếu %d nhân sự (có %d)",
                        req.getWorkDate(), getDayOfWeekVietnamese(req.getWorkDate().getDayOfWeek().getValue()),
                        req.getShiftType().getName(),
                        req.getRequiredStaffCount() - assigned, assigned));
            }
        }

        return warnings;
    }

    private List<Staff> filterBySpecialty(List<Staff> staffList, Integer specialtyId) {
        if (specialtyId == null) return staffList;
        return staffList.stream()
                .filter(s -> s.getSpecialty() != null && s.getSpecialty().getId().equals(specialtyId))
                .collect(Collectors.toList());
    }

    private Staff selectStaffByWorkload(List<Staff> availableStaff, Integer periodId, String shiftTypeId) {
        Staff selected = null;
        long minCount = Long.MAX_VALUE;

        for (Staff staff : availableStaff) {
            long count = scheduleRepository.countByStaffIdAndPeriodId(staff.getId(), periodId);
            if (count < minCount) {
                minCount = count;
                selected = staff;
            }
        }

        return selected;
    }

    private Schedule buildSchedule(SchedulePeriod period, Staff staff, ShiftType shiftType,
                                   LocalDate workDate, ShiftRequirement requirement) {
        // Check DB for existing schedule
        Optional<Schedule> existing = scheduleRepository.findByPeriodIdAndStaffIdAndShiftTypeIdAndWorkDate(
                period.getId(), staff.getId(), shiftType.getId(), workDate);
        if (existing.isPresent()) return null;

        // Check in-memory assignments (for preview mode and same-run conflicts)
        if (hasInMemoryConflict(staff.getId(), workDate, shiftType.getId())) {
            return null;
        }

        return Schedule.builder()
                .period(period)
                .staff(staff)
                .shiftType(shiftType)
                .workDate(workDate)
                .requirement(requirement)
                .hasConflict(false)
                .build();
    }

    private boolean hasInMemoryConflict(Integer staffId, LocalDate workDate, String shiftTypeId) {
        String key = staffId + "_" + workDate;
        Set<String> existingShifts = inMemoryAssignments.get(key);
        if (existingShifts != null) {
            // L01 vs L02/L03/L04: overnight cannot coexist with non-overnight
            // L02 vs L01: L01 already assigned → conflict
            // L02 vs L01: L02 already assigned → conflict
            for (String existingId : existingShifts) {
                if (ConflictDetectionService.SHIFT_TYPE_L01.equals(shiftTypeId)) {
                    // L01 cannot coexist with L02, L03, L04
                    if (ConflictDetectionService.SHIFT_TYPE_L02.equals(existingId) || ConflictDetectionService.SHIFT_TYPE_L03.equals(existingId) || ConflictDetectionService.SHIFT_TYPE_L04.equals(existingId)) {
                        return true;
                    }
                }
                if (ConflictDetectionService.SHIFT_TYPE_L02.equals(shiftTypeId)) {
                    // L02 cannot coexist with L01 (L01 already assigned)
                    if (ConflictDetectionService.SHIFT_TYPE_L01.equals(existingId)) return true;
                }
                if (ConflictDetectionService.SHIFT_TYPE_L03.equals(shiftTypeId) || ConflictDetectionService.SHIFT_TYPE_L04.equals(shiftTypeId)) {
                    // L03 vs L04: cannot both be assigned to same person same day
                    if ((ConflictDetectionService.SHIFT_TYPE_L03.equals(existingId) && ConflictDetectionService.SHIFT_TYPE_L04.equals(shiftTypeId)) ||
                        (ConflictDetectionService.SHIFT_TYPE_L04.equals(existingId) && ConflictDetectionService.SHIFT_TYPE_L03.equals(shiftTypeId))) {
                        return true;
                    }
                    // L03/L04 cannot coexist with L01
                    if (ConflictDetectionService.SHIFT_TYPE_L01.equals(existingId)) return true;
                }
            }
        }

        // Check if this date is a compensation day for the staff
        // L02/L03/L04 cannot be assigned on a day that is a compensation day for this staff
        if (!ConflictDetectionService.SHIFT_TYPE_L01.equals(shiftTypeId)) {
            String compKey = staffId + "_" + workDate.toString();
            if (inMemoryCompensationShiftDates.contains(compKey)) {
                return true;
            }
        }

        // L01 cannot be assigned on a day that is already a compensation day for this staff
        // (from L01 in a previous published period)
        if (ConflictDetectionService.SHIFT_TYPE_L01.equals(shiftTypeId)) {
            String compKey = staffId + "_" + workDate.toString();
            if (allCompensationShiftDates.contains(compKey)) {
                return true;
            }
        }

        return false;
    }

    private void trackAssignment(Staff staff, LocalDate workDate, String shiftTypeId) {
        String key = staff.getId() + "_" + workDate;
        inMemoryAssignments.computeIfAbsent(key, k -> new HashSet<>()).add(shiftTypeId);
        // Also track compensation day if this is L01, so later L02/L03/L04 can't be assigned on that day
        // AND so we know not to assign L01 on this staff's compensation day
        if (ConflictDetectionService.SHIFT_TYPE_L01.equals(shiftTypeId)) {
            LocalDate compDate = compensationDateCalculator.calculateWithoutHolidays(workDate);
            String compKey = staff.getId() + "_" + compDate;
            inMemoryCompensationShiftDates.add(compKey);
            // Also add to all compensation shiftDates to prevent L01 on this day
            allCompensationShiftDates.add(staff.getId() + "_" + compDate.toString());
        }
    }

    private void createCompensationDayForAuto(Schedule schedule) {
        LocalDate shiftDate = schedule.getWorkDate();
        LocalDate compensationDate = compensationDateCalculator.calculate(shiftDate);

        if (compensationDayRepository.findByStaffIdAndCompensationDate(schedule.getStaff().getId(), compensationDate).isPresent()) {
            return;
        }

        CompensationDay compDay = CompensationDay.builder()
                .schedule(schedule)
                .staff(schedule.getStaff())
                .period(schedule.getPeriod())
                .shiftDate(shiftDate)
                .compensationDate(compensationDate)
                .note("Ngày nghỉ bù tự động từ ca L01")
                .build();

        compensationDayRepository.save(compDay);
    }

    private BigDecimal calculateBalanceScore(List<Schedule> schedules, int totalStaff) {
        if (schedules.isEmpty()) return BigDecimal.ZERO;

        Map<Integer, Long> staffScheduleCount = schedules.stream()
                .collect(Collectors.groupingBy(s -> s.getStaff().getId(), Collectors.counting()));

        if (staffScheduleCount.size() <= 1) return BigDecimal.valueOf(100);

        double avg = (double) schedules.size() / totalStaff;
        double variance = staffScheduleCount.values().stream()
                .mapToDouble(Long::doubleValue)
                .map(count -> (count - avg) * (count - avg))
                .average()
                .orElse(0);

        double stdDev = Math.sqrt(variance);
        double cv = avg > 0 ? (stdDev / avg) * 100 : 0;

        return BigDecimal.valueOf(Math.max(0, 100 - cv)).setScale(2, RoundingMode.HALF_UP);
    }

    private void saveMetrics(SchedulePeriod period, String algorithmType, int executionTime,
                             BigDecimal coverageRate, BigDecimal balanceScore, int conflictCount) {
        AlgorithmMetrics metrics = AlgorithmMetrics.builder()
                .period(period)
                .algorithmType(algorithmType)
                .executionTimeMs(executionTime)
                .coverageRate(coverageRate)
                .balanceScore(balanceScore)
                .conflictCount(conflictCount)
                .build();

        metricsRepository.save(metrics);
    }

    private String getDayOfWeekVietnamese(int day) {
        return switch (day) {
            case 1 -> "Thứ 2";
            case 2 -> "Thứ 3";
            case 3 -> "Thứ 4";
            case 4 -> "Thứ 5";
            case 5 -> "Thứ 6";
            case 6 -> "Thứ 7";
            case 7 -> "Chủ Nhật";
            default -> "";
        };
    }

    public List<AlgorithmMetricsDTO> getMetricsByPeriod(Integer periodId) {
        return metricsRepository.findByPeriodId(periodId).stream()
                .map(this::metricsToDTO)
                .toList();
    }

    public List<AlgorithmMetricsDTO> getAllMetrics() {
        return metricsRepository.findAll().stream()
                .map(this::metricsToDTO)
                .toList();
    }

    private AlgorithmMetricsDTO metricsToDTO(AlgorithmMetrics m) {
        return AlgorithmMetricsDTO.builder()
                .id(m.getId())
                .algorithmType(m.getAlgorithmType())
                .executionTimeMs(m.getExecutionTimeMs())
                .coverageRate(m.getCoverageRate())
                .balanceScore(m.getBalanceScore())
                .conflictCount(m.getConflictCount())
                .createdAt(m.getCreatedAt())
                .build();
    }

    private List<ShiftRequirement> sortRequirementsByPriority(List<ShiftRequirement> requirements) {
        return requirements.stream()
                .sorted(Comparator.comparingInt((ShiftRequirement r) -> {
                    String id = r.getShiftType().getId();
                    if (ConflictDetectionService.SHIFT_TYPE_L01.equals(id)) return 0;
                    if (ConflictDetectionService.SHIFT_TYPE_L02.equals(id)) return 1;
                    if (ConflictDetectionService.SHIFT_TYPE_L03.equals(id)) return 2;
                    return 3;
                }))
                .collect(Collectors.toList());
    }

    private Map<LocalDate, List<ShiftRequirement>> groupRequirementsByDate(List<ShiftRequirement> requirements) {
        return requirements.stream().collect(Collectors.groupingBy(ShiftRequirement::getWorkDate));
    }

    private List<Staff> filterAndSortEligibleStaff(List<Staff> pool, ShiftRequirement req,
                                                    Set<Integer> excludedStaffIds, boolean skipCompensationCheck,
                                                    Comparator<Staff> sortComparator) {
        return pool.stream()
                .filter(s -> excludedStaffIds == null || !excludedStaffIds.contains(s.getId()))
                .filter(s -> {
                    if (req.getSpecialty() != null && (s.getSpecialty() == null || !s.getSpecialty().getId().equals(req.getSpecialty().getId()))) {
                        return false;
                    }
                    if (conflictDetectionService.hasAnyConflict(s.getId(), req.getWorkDate(), req.getShiftType().getId(), null, skipCompensationCheck)) {
                        return false;
                    }
                    if (hasInMemoryConflict(s.getId(), req.getWorkDate(), req.getShiftType().getId())) {
                        return false;
                    }
                    return true;
                })
                .sorted(sortComparator)
                .collect(Collectors.toList());
    }

    private Schedule buildAndSaveSchedule(SchedulePeriod period, Staff staff, ShiftRequirement req,
                                         LocalDate workDate, boolean save, List<Schedule> list) {
        Schedule schedule = Schedule.builder()
                .period(period)
                .staff(staff)
                .shiftType(req.getShiftType())
                .workDate(workDate)
                .requirement(req)
                .hasConflict(false)
                .build();
        if (save) {
            Schedule saved = scheduleRepository.save(schedule);
            auditHistoryService.logAction("schedule", saved.getId(), AuditHistory.ActionType.INSERT, null, saved, null);
            list.add(saved);
            return saved;
        } else {
            schedule.setId(null);
            list.add(schedule);
            return schedule;
        }
    }
}
