const { chromium } = require('../frontend/node_modules/playwright');
const fs = require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const out={timestamp:new Date().toISOString(),routes:{},axe:{},race:{},exports:[]};
 const ctx=await browser.newContext({acceptDownloads:true}); const p=await ctx.newPage();
 const logs=[]; const errors=[]; const reqs=[]; const starts=new Map();
 p.on('console',m=>logs.push({type:m.type(),text:m.text()})); p.on('pageerror',e=>errors.push(String(e)));
 p.on('request',r=>{if(r.url().includes('/api/')){starts.set(r,Date.now()); reqs.push({event:'request',method:r.method(),url:r.url(),headers:r.headers(),at:Date.now()})}});
 p.on('response',r=>{if(r.url().includes('/api/')) reqs.push({event:'response',method:r.request().method(),url:r.url(),status:r.status(),latency:Date.now()-(starts.get(r.request())||Date.now()),headers:r.headers(),at:Date.now()})});
 p.on('requestfailed',r=>{if(r.url().includes('/api/')) reqs.push({event:'failed',method:r.method(),url:r.url(),failure:r.failure(),at:Date.now()})});
 await p.goto('http://localhost:3001/login'); await p.locator('#username').fill('admin'); await p.locator('#password').fill('admin123');
 await Promise.all([p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:15000}),p.locator('form').evaluate(f=>f.requestSubmit())]);
 for(const route of ['/reports','/reports/monthly','/reports/statistics','/reports/staff','/reports/conflicts']){
  const n0=reqs.length,l0=logs.length,e0=errors.length; await p.goto('http://localhost:3001'+route); await p.waitForLoadState('networkidle',{timeout:20000}).catch(()=>{}); await p.waitForTimeout(1000);
  const snap=await p.evaluate(()=>({url:location.href,title:document.title,h1:[...document.querySelectorAll('h1')].map(x=>x.textContent.trim()),h2:[...document.querySelectorAll('h2')].map(x=>x.textContent.trim()),tables:[...document.querySelectorAll('table')].map(t=>({label:t.getAttribute('aria-label'),headers:[...t.querySelectorAll('th')].map(x=>x.textContent.trim()),rows:t.querySelectorAll('tbody tr').length})),selects:[...document.querySelectorAll('select')].map(x=>({name:x.labels?.[0]?.textContent.trim()||x.getAttribute('aria-label'),value:x.value,options:x.options.length})),inputs:[...document.querySelectorAll('input')].map(x=>({type:x.type,name:x.labels?.[0]?.textContent.trim()||x.getAttribute('aria-label')||x.placeholder,value:x.value})),buttons:[...document.querySelectorAll('button')].map(x=>({name:x.textContent.trim(),disabled:x.disabled,role:x.getAttribute('role'),selected:x.getAttribute('aria-selected')})),alerts:[...document.querySelectorAll('[role=alert]')].map(x=>x.textContent.trim()),statuses:[...document.querySelectorAll('[role=status]')].map(x=>x.textContent.trim()),scroll:{w:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth},tokenInHtml:/eyJ[a-zA-Z0-9_-]+\./.test(document.documentElement.innerHTML)}));
  out.routes[route]={...snap,network:reqs.slice(n0),console:logs.slice(l0),pageErrors:errors.slice(e0)};
  try{await p.addScriptTag({path:require.resolve('../frontend/node_modules/axe-core/axe.min.js')}); out.axe[route]=await p.evaluate(async()=>{const r=await axe.run();return r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.length,help:v.help,targets:v.nodes.slice(0,3).map(n=>n.target)}))})}catch(e){out.axe[route]={error:String(e)}}
  for(const vp of [{w:390,h:844},{w:768,h:1024}]){await p.setViewportSize({width:vp.w,height:vp.h}); await p.waitForTimeout(100); out.routes[route]['viewport'+vp.w]=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,bodyScrollWidth:document.body.scrollWidth}))} await p.setViewportSize({width:1280,height:720});
 }
 // race selectors: rapid period/filter changes
 for(const route of ['/reports/monthly','/reports/statistics','/reports/staff','/reports/conflicts']){await p.goto('http://localhost:3001'+route); await p.waitForTimeout(1000); const sel=p.locator('main select').first(); const vals=await sel.locator('option').evaluateAll(os=>os.map(o=>o.value).filter(Boolean)); const n=reqs.length;if(vals.length>1){for(let i=0;i<8;i++)await sel.selectOption(vals[i%Math.min(vals.length,3)]);await p.waitForTimeout(2000)} out.race[route]=reqs.slice(n)}
 // navigation persistence
 await p.goto('http://localhost:3001/reports/statistics');await p.waitForTimeout(700);const s=p.locator('#stats-shift-type');const sv=await s.locator('option').evaluateAll(os=>os.map(o=>o.value).filter(Boolean));if(sv[0])await s.selectOption(sv[0]);const before=p.url();await p.reload();await p.waitForTimeout(700);out.navigation={before,after:p.url(),filterAfter:await s.inputValue()};
 // export valid xlsx/pdf plus invalid date; no mutation
 await p.goto('http://localhost:3001/reports/monthly');await p.waitForTimeout(1200);const ec=p.locator('[data-testid=export-controls]').first();
 if(await ec.count()){const starts=ec.locator('input[type=date]');await starts.nth(0).fill('2026-07-20');await starts.nth(1).fill('2026-07-01');out.invalidDate={alert:await ec.locator('[role=alert]').textContent(),disabled:await ec.locator('[data-testid=export-trigger]').isDisabled()};await starts.nth(0).fill('');await starts.nth(1).fill('');for(const fmt of ['excel-schedule','pdf-schedule','excel-workload']){const f=ec.locator('select').last();if((await f.locator(`option[value="${fmt}"]`).count())===0)continue;await f.selectOption(fmt);const n=reqs.length;try{const dl=await Promise.all([p.waitForEvent('download',{timeout:20000}),ec.locator('[data-testid=export-trigger]').click()]);const path=await dl[0].path();const b=fs.readFileSync(path);out.exports.push({fmt,name:dl[0].suggestedFilename(),size:b.length,magic:b.subarray(0,8).toString('hex'),network:reqs.slice(n)})}catch(e){out.exports.push({fmt,error:String(e),network:reqs.slice(n)})}}}
 out.global={console:logs,pageErrors:errors,network:reqs}; fs.writeFileSync('tmp_bench/reports_runtime_audit.json',JSON.stringify(out,null,2)); await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});