package com.hospital.scheduler.digital.sandbox.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * Stores cloned schedule assignments for a sandbox session.
 *
 * <p>Only schedule data is cloned; reference data (Staff, ShiftType, etc.) is shared.
 * This significantly reduces storage requirements.
 *
 * <p>Structure mirrors the real Schedule entity but with sandbox_session FK.
 */
@Entity
@Table(name = "sandbox_assignment",
    indexes = {
        @Index(name = "idx_sandbox_assign_session", columnList = "session_id"),
        @Index(name = "idx_sandbox_assign_slot", columnList = "session_id, slot_id")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SandboxAssignment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Parent sandbox session.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "session_id", nullable = false)
    private SandboxSession session;

    /**
     * Slot ID (mirrors ShiftRequirementInfo.slotId).
     */
    @Column(name = "slot_id", nullable = false)
    private Integer slotId;

    /**
     * Work date (denormalized for faster queries).
     */
    @Column(name = "work_date", nullable = false)
    private LocalDateTime workDate;

    /**
     * Shift type ID (L01, L02, etc.).
     */
    @Column(name = "shift_type_id", nullable = false, length = 8)
    private String shiftTypeId;

    /**
     * Staff ID assigned to this slot.
     */
    @Column(name = "staff_id")
    private Integer staffId;

    /**
     * Staff name (denormalized for display).
     */
    @Column(name = "staff_name", length = 128)
    private String staffName;

    /**
     * Whether this assignment was generated by simulation or from original.
     */
    @Column(name = "is_simulated")
    @Builder.Default
    private Boolean isSimulated = false;

    /**
     * Whether this assignment has a constraint conflict.
     */
    @Column(name = "has_conflict")
    @Builder.Default
    private Boolean hasConflict = false;

    /**
     * Score contribution of this assignment.
     */
    @Column(name = "score_contribution")
    private Double scoreContribution;

    /**
     * Which iteration this assignment was made/changed.
     */
    @Column(name = "iteration_changed")
    private Integer iterationChanged;

    /**
     * Move type that created/changed this assignment.
     */
    @Column(name = "move_type", length = 32)
    private String moveType;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
