package com.hospital.scheduler.service.scheduling;

import com.hospital.scheduler.algorithm.SchedulingResult;
import com.hospital.scheduler.algorithm.ShiftRequirementInfo;
import com.hospital.scheduler.entity.*;
import com.hospital.scheduler.service.ConflictDetectionService;
import com.hospital.scheduler.util.CompensationDateCalculator;
import lombok.extern.slf4j.Slf4j;

import java.time.LocalDate;
import java.util.*;

/**
 * Pure-function helpers for the CSP-MRV-FC algorithm.
 *
 * <p>Extracted from {@link com.hospital.scheduler.service.AutoSchedulingService} during the M07
 * refactor. The actual CSP solver invocation ({@code CSPScheduler.solve / solveForPreview})
 * stays in the facade; this engine contains only the stateless translation and
 * conversion logic.
 *
 * <p>Public helpers:
 * <ul>
 *   <li>{@link #toRequirementInfos} — DB entities → algorithm DTOs</li>
 *   <li>{@link #cspPartialToSchedules} — partial CSP result → transient Schedule entities</li>
 *   <li>{@link #filterSchedulesExcluding} — deduplicate Greedy top-up against CSP partial</li>
 *   <li>{@link #mergeSchedules} — CSP partial + Greedy top-up → single list</li>
 * </ul>
 */
@Slf4j
public final class CspAssignmentEngine {

    private CspAssignmentEngine() {}

    /**
     * Build a unique slot key for an in-memory schedule.
     * Used for deduplication when merging the CSP partial plan with the Greedy top-up.
     */
    public static String scheduleSlotKey(Schedule s) {
        return s.getStaff().getId() + "_" + s.getShiftType().getId() + "_" + s.getWorkDate();
    }

    /**
     * Translate DB requirements → algorithm DTOs so the CSP solver can consume them.
     * Used by both the full scheduling path ({@code runCsp}) and the re-solve
     * path ({@code incrementalReassign}).
     */
    public static List<ShiftRequirementInfo> toRequirementInfos(List<ShiftRequirement> requirements) {
        if (requirements == null) return List.of();
        return requirements.stream()
                .map(r -> new ShiftRequirementInfo(
                        r.getShiftType().getId(),
                        r.getWorkDate(),
                        r.getRequiredStaffCount(),
                        r.getSpecialty() != null ? r.getSpecialty().getId() : null))
                .toList();
    }

    /**
     * Convert a CSP partial assignment result into transient {@link Schedule} entities
     * for merging with the Greedy top-up.
     *
     * <p>Two-pass algorithm:
     * <ol>
     *   <li>First pass: collect compensation days generated by L01 assignments in the
     *       partial plan so the second pass can skip them.</li>
     *   <li>Second pass: build transient Schedule entities, skipping any assignment
     *       that lands on a self-generated compensation day.</li>
     * </ol>
     *
     * @param calculator used to derive the compensation date for each L01 work date
     */
    public static List<Schedule> cspPartialToSchedules(
            SchedulingResult cspResult,
            SchedulePeriod period,
            List<ShiftRequirement> requirements,
            List<Staff> activeStaff,
            CompensationDateCalculator calculator) {

        Set<String> compDays = new HashSet<>();
        // First pass: collect comp days from L01 assignments in the partial plan.
        for (Map.Entry<String, String> entry : cspResult.getAssignments().entrySet()) {
            if (!ConflictDetectionService.SHIFT_TYPE_L01.equals(entry.getValue())) continue;
            String[] parts = entry.getKey().split("\\|");
            if (parts.length < 2) continue;
            LocalDate workDate = LocalDate.parse(parts[1]);
            LocalDate compDate = calculator.calculate(workDate);
            if (compDate != null) {
                compDays.add(parts[0] + "_" + compDate);
            }
        }

        List<Schedule> partial = new ArrayList<>();
        Map<Integer, Staff> staffMap = new HashMap<>();
        for (Staff s : activeStaff) staffMap.putIfAbsent(s.getId(), s);

        for (Map.Entry<String, String> entry : cspResult.getAssignments().entrySet()) {
            String[] parts = entry.getKey().split("\\|");
            if (parts.length != 2) continue;
            Integer staffId = Integer.parseInt(parts[0]);
            LocalDate workDate = LocalDate.parse(parts[1]);
            String shiftTypeId = entry.getValue();

            // Skip if this slot lands on a self-generated compensation day.
            if (compDays.contains(staffId + "_" + workDate)) continue;

            Staff staff = staffMap.get(staffId);
            if (staff == null) continue;

            ShiftRequirement req = requirements.stream()
                    .filter(r -> r.getWorkDate().equals(workDate)
                            && r.getShiftType().getId().equals(shiftTypeId))
                    .findFirst().orElse(null);
            if (req == null) continue;

            partial.add(Schedule.builder()
                    .period(period)
                    .staff(staff)
                    .shiftType(req.getShiftType())
                    .workDate(workDate)
                    .requirement(req)
                    .hasConflict(false)
                    .build());
        }

        log.info("Converted CSP partial: {} assignments kept ({} were skipped on comp days or unmatched)",
                partial.size(), cspResult.getScheduleCount() - partial.size());
        return partial;
    }

    /**
     * Filter {@code candidates} to remove any slot already present in {@code kept}.
     * Used to deduplicate the Greedy top-up against the CSP partial plan.
     */
    public static List<Schedule> filterSchedulesExcluding(List<Schedule> candidates, List<Schedule> kept) {
        if (candidates == null || candidates.isEmpty()) return List.of();
        Set<String> keptKeys = new HashSet<>(kept.size() * 2);
        for (Schedule s : kept) keptKeys.add(scheduleSlotKey(s));
        List<Schedule> filtered = new ArrayList<>();
        for (Schedule s : candidates) {
            if (!keptKeys.contains(scheduleSlotKey(s))) {
                filtered.add(s);
            }
        }
        return filtered;
    }

    /**
     * Merge two schedule lists: CSP partial slots first (they take priority),
     * then Greedy top-up slots. The top-up list should already be deduplicated
     * via {@link #filterSchedulesExcluding}.
     */
    public static List<Schedule> mergeSchedules(List<Schedule> cspPartial, List<Schedule> topUp) {
        List<Schedule> merged = new ArrayList<>(
                (cspPartial != null ? cspPartial.size() : 0)
                + (topUp != null ? topUp.size() : 0));
        if (cspPartial != null) merged.addAll(cspPartial);
        if (topUp != null) merged.addAll(topUp);
        return merged;
    }
}
