package com.hospital.scheduler.algorithm;

import com.hospital.scheduler.entity.LeaveRequest;
import com.hospital.scheduler.entity.Staff;
import com.hospital.scheduler.util.CompensationDateCalculator;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.*;

/**
 * Fitness function and constraint checker for genetic algorithm scheduling.
 * 
 * Constraints:
 * C1: L01 + L02 same staff same day = CONFLICT
 * C2: L03 + L04 same staff same day = CONFLICT
 * C3: Staff cannot work on leave days
 * C4: Staff cannot work on compensation days
 * C5: Only 1 L01 per day (per spec)
 */
@Component
public class SchedulingFitnessFunction {

    private final CompensationDateCalculator compensationDateCalculator;

    public SchedulingFitnessFunction(CompensationDateCalculator compensationDateCalculator) {
        this.compensationDateCalculator = compensationDateCalculator;
    }

    /**
     * Evaluate fitness of a chromosome.
     * Higher fitness = better solution.
     *
     * Fitness formula:
     * fitness = base - conflictPenalty + balanceBonus + coverageBonus
     *
     * Each assigned slot contributes a {@link #SHIFT_WEIGHT} (by shift type)
     * to the coverage bonus, so heavier shifts (L01 24/24) naturally pull
     * more on the fairness signal — under-assigning L01 is penalized the
     * same way a thin coverage of L02 is. Otherwise a chromosome that
     * filled only the lightest L03/L04 shifts could look "balanced" while
     * leaving L01 coverage behind.
     *
     * @param chromosome The chromosome to evaluate
     * @param leaveRequests Approved leave requests
     * @param existingCompensationDays Existing compensation days (staffId_date format)
     * @param excludedStaffIds Staff excluded from scheduling
     * @param config GA configuration
     * @return Fitness score (higher is better)
     */
    public double evaluate(
            ScheduleChromosome chromosome,
            List<LeaveRequest> leaveRequests,
            Set<String> existingCompensationDays,
            Set<Integer> excludedStaffIds,
            GeneticAlgorithmConfig config) {

        // Build lookup maps for fast constraint checking
        Set<String> leaveDays = buildLeaveDaySet(leaveRequests);
        Map<Integer, Set<LocalDate>> staffCompDays = buildCompensationDayMap(existingCompensationDays);
        Map<Integer, Set<LocalDate>> staffLeaves = buildStaffLeaveMap(leaveRequests);

        // Calculate conflicts
        int conflicts = countConflicts(chromosome, leaveDays, staffCompDays, staffLeaves, excludedStaffIds);

        // Calculate coverage (weighted by shift type)
        double coverage = chromosome.calculateWeightedCoverage(SHIFT_WEIGHT);

        // Calculate balance (weighted by shift type)
        double balance = chromosome.calculateWeightedBalance(SHIFT_WEIGHT);

        // Update chromosome stats
        chromosome.setConflictCount(conflicts);
        chromosome.setCoverageRate(coverage);
        chromosome.setBalanceScore(balance);

        // Fitness = base - conflictPenalty + balanceBonus + coverageBonus
        double baseFitness = 1000.0;
        double conflictPenalty = conflicts * config.conflictWeight();
        double balanceBonus = balance * config.balanceWeight();
        double coverageBonus = coverage * config.coverageWeight();

        double fitness = baseFitness - conflictPenalty + balanceBonus + coverageBonus;
        chromosome.setFitness(fitness);

        return fitness;
    }

    /**
     * Per-shift-type weight used when calculating coverage & balance bonuses.
     * L01 (24/24) is the most physically demanding shift and earns the highest
     * weight; L03/L04 are lighter so they don't dominate the balance signal.
     */
    private static final Map<String, Double> SHIFT_WEIGHT = Map.of(
            CspConstants.DIRECT_24H, 3.0,
            CspConstants.THONG_TAM, 1.5,
            CspConstants.DICH_VU, 1.0,
            CspConstants.CHUYEN_GIA, 1.0
    );

    /**
     * Count constraint violations in chromosome.
     */
    public int countConflicts(
            ScheduleChromosome chromosome,
            Set<String> leaveDays,
            Map<Integer, Set<LocalDate>> staffCompDays,
            Map<Integer, Set<LocalDate>> staffLeaves,
            Set<Integer> excludedStaffIds) {

        int conflicts = 0;
        List<ShiftRequirementInfo> requirements = chromosome.getRequirements();

        // Build compensation days from L01 assignments IN THIS CHROMOSOME
        // This is CRITICAL - we must check against compensation days that would be generated by L01 assignments
        Map<Integer, Set<LocalDate>> chromosomeCompDays = buildCompensationDaysFromChromosome(chromosome);
        
        // Merge with existing compensation days
        for (Map.Entry<Integer, Set<LocalDate>> entry : chromosomeCompDays.entrySet()) {
            staffCompDays.computeIfAbsent(entry.getKey(), k -> new HashSet<>()).addAll(entry.getValue());
        }

        // Group assignments by (staff, date) to check for same-day conflicts
        Map<String, List<String>> staffDateShifts = new HashMap<>();

        for (int i = 0; i < requirements.size(); i++) {
            ShiftRequirementInfo req = requirements.get(i);
            Staff staff = chromosome.getStaffAt(i);

            if (staff == null) continue;
            if (excludedStaffIds != null && excludedStaffIds.contains(staff.getId())) {
                conflicts++;
                continue;
            }

            LocalDate workDate = req.workDate();
            String shiftType = req.shiftTypeId();
            String key = staff.getId() + "_" + workDate;

            // Check leave
            if (staffLeaves.containsKey(staff.getId()) && 
                staffLeaves.get(staff.getId()).contains(workDate)) {
                conflicts++;
                continue;
            }

            // Check compensation day (from both existing AND chromosome-generated)
            if (staffCompDays.containsKey(staff.getId()) &&
                staffCompDays.get(staff.getId()).contains(workDate)) {
                conflicts++;
                continue;
            }

            // Check holiday
            if (leaveDays.contains(workDate.toString())) {
                conflicts++;
                continue;
            }

            // Track for same-day conflict check
            staffDateShifts.computeIfAbsent(key, k -> new ArrayList<>()).add(shiftType);
        }
        
        // Check same-day conflicts: L01 vs L02, L03 vs L04
        for (List<String> shifts : staffDateShifts.values()) {
            boolean hasL01 = shifts.contains(CspConstants.DIRECT_24H);
            boolean hasL02 = shifts.contains(CspConstants.THONG_TAM);
            boolean hasL03 = shifts.contains(CspConstants.DICH_VU);
            boolean hasL04 = shifts.contains(CspConstants.CHUYEN_GIA);

            if (hasL01 && hasL02) conflicts++;
            if (hasL03 && hasL04) conflicts++;
        }

        // Check L01 back-to-back conflict: staff cannot work L01 on consecutive days
        // Track L01 assignments by staff
        Map<Integer, Set<LocalDate>> staffL01Dates = new HashMap<>();
        for (int i = 0; i < requirements.size(); i++) {
            ShiftRequirementInfo req = requirements.get(i);
            Staff staff = chromosome.getStaffAt(i);
            if (staff == null) continue;
            if (!CspConstants.DIRECT_24H.equals(req.shiftTypeId())) continue;

            staffL01Dates.computeIfAbsent(staff.getId(), k -> new HashSet<>()).add(req.workDate());
        }

        // Check for consecutive L01 assignments
        for (Map.Entry<Integer, Set<LocalDate>> entry : staffL01Dates.entrySet()) {
            Set<LocalDate> dates = entry.getValue();
            for (LocalDate date : dates) {
                // Check N-1 and N+1 (adjacent days)
                if (dates.contains(date.minusDays(1)) || dates.contains(date.plusDays(1))) {
                    conflicts++;
                    break; // Count once per staff with back-to-back L01
                }
            }
        }

        // Count unassigned slots as penalty
        conflicts += chromosome.getUnassignedCount();
        
        return conflicts;
    }

    /**
     * Build set of holiday dates.
     */
    private Set<String> buildLeaveDaySet(List<LeaveRequest> leaveRequests) {
        Set<String> holidays = new HashSet<>();
        for (LeaveRequest req : leaveRequests) {
            if (req.getStatus() == LeaveRequest.LeaveStatus.APPROVED) {
                holidays.add(req.getStartDate().toString());
            }
        }
        return holidays;
    }

    /**
     * Build map of staff -> compensation dates.
     */
    private Map<Integer, Set<LocalDate>> buildCompensationDayMap(Set<String> existingCompensationDays) {
        Map<Integer, Set<LocalDate>> map = new HashMap<>();
        for (String comp : existingCompensationDays) {
            String[] parts = comp.split("_");
            if (parts.length >= 2) {
                int staffId = Integer.parseInt(parts[0]);
                LocalDate date = LocalDate.parse(parts[1]);
                map.computeIfAbsent(staffId, k -> new HashSet<>()).add(date);
            }
        }
        return map;
    }

    /**
     * Build map of staff -> leave dates.
     */
    private Map<Integer, Set<LocalDate>> buildStaffLeaveMap(List<LeaveRequest> leaveRequests) {
        Map<Integer, Set<LocalDate>> map = new HashMap<>();
        for (LeaveRequest req : leaveRequests) {
            if (req.getStatus() == LeaveRequest.LeaveStatus.APPROVED) {
                map.computeIfAbsent(req.getStaff().getId(), k -> new HashSet<>())
                        .add(req.getStartDate());
            }
        }
        return map;
    }
    
    /**
     * Build compensation days from L01 assignments in the chromosome.
     * When a staff is assigned L01 on date N, they get compensation day on date N+1 (or calculated date).
     */
    private Map<Integer, Set<LocalDate>> buildCompensationDaysFromChromosome(ScheduleChromosome chromosome) {
        Map<Integer, Set<LocalDate>> compDays = new HashMap<>();
        List<ShiftRequirementInfo> requirements = chromosome.getRequirements();
        
        for (int i = 0; i < requirements.size(); i++) {
            ShiftRequirementInfo req = requirements.get(i);
            Staff staff = chromosome.getStaffAt(i);
            
            if (staff == null) continue;
            if (!CspConstants.DIRECT_24H.equals(req.shiftTypeId())) continue;
            
            // Calculate compensation date for L01 assignment
            LocalDate compDate = compensationDateCalculator.calculate(req.workDate());
            if (compDate != null) {
                compDays.computeIfAbsent(staff.getId(), k -> new HashSet<>()).add(compDate);
            }
        }
        
        return compDays;
    }

    /**
     * Check if a specific assignment is valid.
     */
    public boolean isValidAssignment(Staff staff, LocalDate workDate, String shiftType,
            Set<String> leaveDays, Map<Integer, Set<LocalDate>> staffCompDays,
            Map<Integer, Set<LocalDate>> staffLeaves, Set<Integer> excludedStaffIds) {
        
        if (staff == null || excludedStaffIds.contains(staff.getId())) return false;
        if (leaveDays.contains(workDate.toString())) return false;
        if (staffLeaves.containsKey(staff.getId()) && staffLeaves.get(staff.getId()).contains(workDate)) return false;
        if (staffCompDays.containsKey(staff.getId()) && staffCompDays.get(staff.getId()).contains(workDate)) return false;
        
        return true;
    }

    /**
     * Get valid staff candidates for a requirement.
     */
    public List<Integer> getValidStaffIndices(
            ShiftRequirementInfo req,
            List<Staff> staffPool,
            Set<String> leaveDays,
            Map<Integer, Set<LocalDate>> staffCompDays,
            Map<Integer, Set<LocalDate>> staffLeaves,
            Set<Integer> excludedStaffIds,
            Set<String> alreadyAssignedStaffDateKeys) {
        
        List<Integer> validIndices = new ArrayList<>();
        LocalDate workDate = req.workDate();
        String shiftType = req.shiftTypeId();
        String dateKey = workDate.toString();
        
        for (int i = 0; i < staffPool.size(); i++) {
            Staff staff = staffPool.get(i);
            
            if (!isValidAssignment(staff, workDate, shiftType, leaveDays, staffCompDays, staffLeaves, excludedStaffIds)) {
                continue;
            }
            
            // Check if staff already assigned to another shift on same day
            String staffDateKey = staff.getId() + "_" + dateKey;
            if (alreadyAssignedStaffDateKeys.contains(staffDateKey)) {
                continue;
            }
            
            // Check same-day conflict: L01 vs L02, L03 vs L04
            // For L01, check if staff already assigned to L02 on same day
            // For L02, check if staff already assigned to L01 on same day
            // etc.
            
            validIndices.add(i);
        }
        
        return validIndices;
    }
}
