package com.hospital.scheduler.dto.response;

import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AutoScheduleResponse {

    private boolean success;
    private String message;
    private Integer periodId;
    private String algorithmType;
    private Integer executionTimeMs;
    private BigDecimal coverageRate;
    private BigDecimal balanceScore;
    private Integer conflictCount;
    private Integer totalSchedulesCreated;
    private List<ScheduleSummary> schedules;
    private List<GeneratedRequirementInfo> generatedRequirements;
    private List<Integer> excludedStaffIds;
    private List<Map<String, Object>> unassignedDays;
    private LocalDateTime executedAt;

    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class ScheduleSummary {
        private Integer scheduleId;
        private Integer staffId;
        private String staffName;
        private String workDate;
        private String shiftTypeId;
        private String shiftTypeName;
    }

    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class GeneratedRequirementInfo {
        private String workDate;
        private String shiftTypeId;
        private String shiftTypeName;
        private Integer requiredStaffCount;
        private String specialtyName;
        private Boolean wasAutoGenerated;
    }
}
